import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  vus: Number(__ENV.VUS || 5),
  duration: __ENV.DURATION || '20s',
  thresholds: {
    http_req_failed: ['rate<0.1'],
    http_req_duration: ['p(95)<1500'],
  },
};

const BASE_URL = (__ENV.BASE_URL || 'http://localhost:5000/api').replace(/\/$/, '');
const AUTH_TOKEN = __ENV.AUTH_TOKEN || '';
const PROFESSIONAL_ID = __ENV.PROFESSIONAL_ID || '00000000-0000-4000-8000-000000000001';
const CATEGORY_ID = __ENV.CATEGORY_ID || '';

export default function () {
  const payload = JSON.stringify({
    professional_id: PROFESSIONAL_ID,
    category_id: CATEGORY_ID || null,
    title: __ENV.BOOKING_TITLE || 'k6 booking smoke test',
    description: 'Generated by k6 smoke test',
    service_address: __ENV.SERVICE_ADDRESS || 'MG Road, Bengaluru',
    preferred_date: __ENV.PREFERRED_DATE || new Date(Date.now() + 86400000).toISOString(),
  });

  const headers = { 'Content-Type': 'application/json' };
  if (AUTH_TOKEN) headers.Authorization = 'Bearer ' + AUTH_TOKEN;

  const res = http.post(`${BASE_URL}/bookings`, payload, {
    headers,
  });

  check(res, {
    'booking request accepted': (r) => [200, 201, 400, 404].includes(r.status),
  });
  sleep(1);
}
